### PR TITLE
On undefined fullscreen key sequence, hardcode to F11

### LINKED ISSUE #1067: REGRESSION: Fullscreen shortcut (F11) not working on WSL
I am using WSL (with Ubuntu on Windows 11) and I noticed that F11 is not working. As shown below, even while navigating the menu, a shortcut for the action is not available (pressing the button works).

Screenshot_3

Printing the value of  `QKeySequence::FullScreen` it gives an empty string. So I assume that because it is launching from WSL into the Windows environment, it cannot handle deciding what platform it is in, so it ends up undefined.

I will make a fix for the issue, since it might be possible to happen in other instances as well and it also helps during development.

### PR DESCRIPTION
**Pull request by sgourdas**
This closes #1067, by adding a condition to check if the fullscreen key sequence is undefined and in that case hardcode it with F11

### CODE REVIEW

File: src/kiwixapp.cpp [hunk 1]
```diff
@@ -413,8 +413,13 @@ void KiwixApp::createActions()
...
             this, [=]() { getTabWidget()->openFindInPageBar(); });
-
-    CREATE_ACTION_ICON_SHORTCUT(ToggleFullscreenAction, "full-screen-enter", gt("set-fullscreen"),  QKeySequence::FullScreen);
+    
+    bool fullScreenKeyUndefined = (QKeySequence(QKeySequence::FullScreen).toString()).isEmpty();
+    if (fullScreenKeyUndefined) {
+        CREATE_ACTION_ICON_SHORTCUT(ToggleFullscreenAction, "full-screen-enter", gt("set-fullscreen"), Qt::Key_F11);
+    } else {
+        CREATE_ACTION_ICON_SHORTCUT(ToggleFullscreenAction, "full-screen-enter", gt("set-fullscreen"), QKeySequence::FullScreen);
+    }
```
Comment (veloman-yunkan) [inline src/kiwixapp.cpp:422]: 1. Why don't you use [`QKeySequence::isEmpty()`](https://doc.qt.io/qt-5/qkeysequence.html#isEmpty)?
2. The difference between your two `CREATE_ACTION_ICON_SHORTCUT()` lines is only in the last argument and I'd rather have the duplication eliminated by isolating the said difference into a constant that would be passed as the last argument:

```c++
    const auto fullScreenKeySeq = QKeySequence(QKeySequence::FullScreen).isEmpty()
                                ? Qt::Key_F11
                                : QKeySequence::FullScreen;
```

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]
LGTMBCBMSB

Can you decode that abbreviation based on my feedback below? :smiley:

File: src/kiwixapp.cpp (hunk 1 above)
Comment (sgourdas) [reply src/kiwixapp.cpp:422]: It "Looks Good To Me But Could Be Made Simpler By Moving Said Behavior" to me as well! 😃

Maybe it is not a good idea to do PRs late at night after work 😢

Totally agree with you.

Comment (veloman-yunkan) [reply src/kiwixapp.cpp:422]: > It "Looks Good To Me But Could Be Made Simpler By ... Moving Said Behavior" to me as well!

Almost there! Actually, I meant ""Looks Good To Me But Can Be Made Slightly Better"

Comment (sgourdas) [reply src/kiwixapp.cpp]: Ah... I thought it would have to be continued below :| Not for me ig 

LGTMNLMKITM 🫡

**Review by veloman-yunkan — APPROVED** [review]
Thanks for the PR!

**Comment by veloman-yunkan** [comment]
@sgourdas Can you please squash your commit into one?

**Comment by veloman-yunkan** [comment]
> @sgourdas Can you please squash your commits into one?

@sgourdas Please ignore my previous comment since the PR has already been merged.

**Comment by sgourdas** [comment]
Will keep in mind for the next one @veloman-yunkan. Thanks for the guidance.

**Comment by veloman-yunkan** [comment]
@sgourdas Since you are going to take my (cancelled) request as a guidance (which it was not) I will elaborate it into one. Squashing all commits of a PR is not a rule. The PR at the time of the merge should consist of a series of changes (commits) representing the cleanest way of achieving the PR's purpose. Commits in the PR must be small to an extent that the essence of every change can be accurately summarized in the (short) title of the commit message. Intermediate changes (like addressing review comments of cosmetic nature, fixing silly bugs introduced be earlier commits, etc) must not pollute the history of the main branch and must be properly squashed into other commits.

File: src/kiwixapp.cpp (hunk 1 above)
Comment (veloman-yunkan) [reply src/kiwixapp.cpp]: > LGTMNLMKITM 🫡

I can debreviate it in one of three ways but I am not sure which one it actually stands for: 

1. Looks good to me now. Let me know if that's marvelous.
2. Lest `git` triggers mysterious nonsense, let my kittens ingest their milk.
3. Little Grandpa took my neighbour's last mathematical kidney in the meantime.
