### PR TITLE
Correctly handle redirection in zim file.

### LINKED ISSUE #384: Links broken in Sotoki ZIM files
Steps:
* Download https://download.kiwix.org/zim/stack_exchange/3dprinting.stackexchange.com_en_all_2020-01.zim
* Click on the first question
* Click on the first question in the "Related" box (top right)

I get:
* Blanck page

I want:
* The proper article

Remark: Things work fine with kiwix-serve

### PR DESCRIPTION
**Pull request by mgautierfr**
Sotoki zim file use redirection to article not in the same "directory".
So it breaks relative urls.

Instead of providing the content of the target entry, we must redirect
to the target entry. So, relative url are not broken.

Fix #384

### CODE REVIEW

File: src/urlschemehandler.cpp [hunk 1]
```diff
@@ -42,12 +42,19 @@ UrlSchemeHandler::handleContentRequest(QWebEngineUrlRequestJob *request)
...
         }
     }
+    bool isRedirect = entry.isRedirect();
     try {
         entry = entry.getFinalEntry();
     } catch (kiwix::NoEntry&) {
         request->fail(QWebEngineUrlRequestJob::UrlNotFound);
         return;
     }
+    if (isRedirect) {
```
Comment (jetownfeve21) [inline src/urlschemehandler.cpp]: We only use this variable here. Maybe we could use `entry.isRedirect()` directly.

**Comment by jetownfeve21** [comment]
fix #206 too
