### PR TITLE
fix: deactivate menu entries when not actionable

### LINKED ISSUE #1318: Deactivate menu entries when not actionable
In the following menu and sub menu, when on the library, we have many items which are actionable/clickable but which do nothing and no sense outside the context of an article. They should be deactivated (many are already)... and reactivated when an article tab is open
Image

### PR DESCRIPTION
**Pull request by etude11**
Fix #1318

### CODE REVIEW

File: src/kiwixapp.cpp [hunk 1]
```diff
@@ -507,18 +508,40 @@ void KiwixApp::postInit() {
...
     app->getAction(KiwixApp::ZoomResetAction)->setDisabled(libraryOrSettingsTab);
-    app->getAction(KiwixApp::RandomArticleAction)->setDisabled(libraryOrSettingsTab);
-    app->getAction(KiwixApp::OpenHomePageAction)->setDisabled(libraryOrSettingsTab);
+
+    // File operations
+    app->getAction(KiwixApp::PrintAction)->setDisabled(libraryOrSettingsTab);
+    app->getAction(KiwixApp::SavePageAsAction)->setDisabled(libraryOrSettingsTab);
+    app->getAction(KiwixApp::OpenMultiZimAction)->setDisabled(!hasZimFile);
+    app->getAction(KiwixApp::ExportReadingListAction)->setDisabled(!hasZimFile);
+    app->getAction(KiwixApp::ImportReadingListAction)->setDisabled(!hasZimFile);
```
Comment (veloman-yunkan) [inline src/kiwixapp.cpp:544]: None of these actions is directly related to the ZIM file associated with the current tab.
- Multi-ZIM search options (yes, the action name is quite misleading - it is not a file operation and should probably be moved to a different group) should work on any tab (so that you can search in any ZIM file without first having to open that ZIM file in a tab);
- Bookmarks (reading-list) sidebar is displayed only in a ZIM tab, however the reading list is not bound to any particular ZIM file.

File: src/kiwixapp.cpp [hunk 2]
```diff
@@ -507,18 +508,40 @@ void KiwixApp::postInit() {
...
+    app->getAction(KiwixApp::SearchArticleAction)->setDisabled(libraryOrSettingsTab);
     app->getAction(KiwixApp::ZoomInAction)->setDisabled(libraryOrSettingsTab);
     app->getAction(KiwixApp::ZoomOutAction)->setDisabled(libraryOrSettingsTab);
     app->getAction(KiwixApp::ZoomResetAction)->setDisabled(libraryOrSettingsTab);
-    app->getAction(KiwixApp::RandomArticleAction)->setDisabled(libraryOrSettingsTab);
-    app->getAction(KiwixApp::OpenHomePageAction)->setDisabled(libraryOrSettingsTab);
+
+    // File operations
+    app->getAction(KiwixApp::PrintAction)->setDisabled(libraryOrSettingsTab);
+    app->getAction(KiwixApp::SavePageAsAction)->setDisabled(libraryOrSettingsTab);
```
Comment (veloman-yunkan) [inline src/kiwixapp.cpp:541]: I don't think that it makes sense to print or save an empty content tab (hence, `libraryOrSettingsTab` -> `!hasZimFile`).

File: src/kiwixapp.cpp [hunk 3]
```diff
@@ -507,18 +508,40 @@ void KiwixApp::postInit() {
...
+    app->getAction(KiwixApp::ReadTextAction)->setDisabled(libraryOrSettingsTab);
+    app->getAction(KiwixApp::ReadStopAction)->setDisabled(libraryOrSettingsTab);
+    app->getAction(KiwixApp::ToggleTTSLanguageAction)->setDisabled(libraryOrSettingsTab);
+    app->getAction(KiwixApp::ToggleTTSVoiceAction)->setDisabled(libraryOrSettingsTab);
+    app->getAction(KiwixApp::IncreaseTTSSpeedAction)->setDisabled(libraryOrSettingsTab);
+    app->getAction(KiwixApp::DecreaseTTSSpeedAction)->setDisabled(libraryOrSettingsTab);
+
+    // Search & zoom
     app->getAction(KiwixApp::FindInPageAction)->setDisabled(libraryOrSettingsTab);
+    app->getAction(KiwixApp::SearchArticleAction)->setDisabled(libraryOrSettingsTab);
```
Comment (veloman-yunkan) [inline src/kiwixapp.cpp:534]: Multi-zim search options (hiding under the misleadingly named `OpenMultiZimAction` action) make it possible searching in any ZIM file while on any tab. It can be a confusing experience on the library and/or settings tab (because of the default selection of the ZIM file to search in) but we shouldn't rather fix it instead of disabling that functionality.

File: src/kiwixapp.cpp [hunk 4]
```diff
@@ -85,7 +85,8 @@ void KiwixApp::init()
 
     setApplicationName("Kiwix");
     setDesktopFileName("kiwix.desktop");
-    setStyleSheet(parseStyleFromFile(":/css/style.css"));
+    setStyleSheet(parseStyleFromFile(":/css/style.css") 
+                  + "\nQMenu::item:disabled { color: gray; }");
```
[the remark this answers is not in the document]
Comment (etude11) [reply src/kiwixapp.cpp:89]: No reason in particular, for some reason back then which I've resolved(internal issues), I wanted to directly edit the main file, I can add it to style.css if you want.

**Comment by etude11** [comment]
I'll fix all the issues mentioned in review asap.

Thanks.

File: src/kiwixapp.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (veloman-yunkan) [reply src/kiwixapp.cpp:89]: Yes, please. BTW, why is this needed at all? What does a disabled menu item look like by default?

**Comment by etude11** [comment]
I've fixed all the requested issues. Could you kindly review.

File: resources/css/style.css [hunk 5]
```diff
@@ -554,3 +554,4 @@ TextToSpeechBar QAbstractItemView QScrollBar {
 TextToSpeechBar QAbstractItemView QScrollBar::handle {
     background-color: grey;
 }
+QMenu::item:disabled { color: gray; }
```
Comment (veloman-yunkan) [inline resources/css/style.css:557]: Please put this beside other `QMenu` related CSS

File: src/kiwixapp.cpp [hunk 6]
```diff
@@ -507,18 +507,38 @@ void KiwixApp::postInit() {
...
+    app->getAction(KiwixApp::ReadTextAction)->setDisabled(libraryOrSettingsTab);
+    app->getAction(KiwixApp::ReadStopAction)->setDisabled(libraryOrSettingsTab);
+    app->getAction(KiwixApp::ToggleTTSLanguageAction)->setDisabled(libraryOrSettingsTab);
+    app->getAction(KiwixApp::ToggleTTSVoiceAction)->setDisabled(libraryOrSettingsTab);
+    app->getAction(KiwixApp::IncreaseTTSSpeedAction)->setDisabled(libraryOrSettingsTab);
+    app->getAction(KiwixApp::DecreaseTTSSpeedAction)->setDisabled(libraryOrSettingsTab);
+
+    // Search & zoom
     app->getAction(KiwixApp::FindInPageAction)->setDisabled(libraryOrSettingsTab);
+    // app->getAction(KiwixApp::SearchArticleAction)->setDisabled(libraryOrSettingsTab);
```
Comment (veloman-yunkan) [inline src/kiwixapp.cpp:533]: Remove this

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]
After addressing the new feedback please squash your changes into a single commit so that we can merge the PR without an extra iteration.

**Comment by etude11** [comment]
I have squashed the commits into one. Ignore the other commit showing up from the other author. Thanks for the guidance.

File: resources/css/style.css [hunk 7]
```diff
@@ -180,6 +180,7 @@ QMenu::item:selected {
     border: 1px solid #3366CC;
 }
 
+QMenu::item:disabled { color: gray; }
```
Comment (veloman-yunkan) [inline resources/css/style.css:183]: Please make the formatting consistent with the rest of CSS code.

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]
We cannot ignore the other commit. Please rebase your PR so that it contains only *your* changes. Also please clean-up the description of your commit (eliminate the traces of it being a result of a squash operation). I am also taking this opportunity to request a small beautification in the CSS file.

**Comment by etude11** [comment]
I've the completed the requested.

**Review by kelson42 — APPROVED** [review]
Sorry for the big delay in reviewing my part. After a very quick overview, it looks good to me. @etude11 Thx!!!!
