### PR TITLE
Ctrl + Click on external link doesn't open a new empty tab

### LINKED ISSUE #326: Open in a new tab does not work fine with external links
On my Windows 10 with kiwix-desktop_windows_x64_2.0-rc3, when ctrl+clicking an external url in a page, Kiwix opens an empty tab then Chrome(the default system url opener) is started for that url.

### PR DESCRIPTION
**Pull request by jetownfeve21**
Connect the &QWebEnginePage::linkHovered signal to set the m_linkHovered
member.
The Ctrl + Click event is intercepted to directly open the m_linkHovered
variable if it's an external link

fix #326

### CODE REVIEW

**Comment by kelson42** [comment]
@jetownfeve21 Nice to see this PR!

**Comment by kelson42** [comment]
@mgautierfr Could you please review this to merge before 2.0 release?

File: src/webview.cpp [hunk 1]
```diff
@@ -75,6 +79,13 @@ bool WebView::eventFilter(QObject *src, QEvent *e)
         if (we->modifiers() == Qt::ControlModifier)
             return true;
     }
+    if (e->type() == QEvent::MouseButtonRelease) {
+        auto me = static_cast<QMouseEvent *>(e);
+        if (me->modifiers() == Qt::ControlModifier && !m_linkHovered.startsWith("zim://")) {
```
Comment (mgautierfr) [inline src/webview.cpp]: There is two way to open a link in a new tab : with Ctrl-click and middle click.
You are catching the ControlModifier but you must also catch the middleButton.
