### PR TITLE
Fix random crash

### LINKED ISSUE #160: kiwix-desktop sometimes crashes when opening a zim file from file explorer

### PR DESCRIPTION
**Pull request by jetownfeve21**
WIP

fix #160

### CODE REVIEW

File: src/readinglistbar.cpp [hunk 1]
```diff
@@ -55,5 +55,5 @@ void ReadingListBar::on_itemActivated(QListWidgetItem* item)
     url.setScheme("zim");
     url.setHost(QString::fromStdString(bookmark.getBookId())+".zim");
     url.setPath(QString::fromStdString(bookmark.getUrl()));
-    KiwixApp::instance()->openUrl(url);
+    KiwixApp::instance()->openUrl(url, false);
```
Comment (jetownfeve21) [inline src/readinglistbar.cpp]: only to facilitate all the manipulations to reproduce the crash

File: src/urlschemehandler.cpp [hunk 2]
```diff
@@ -49,7 +49,8 @@ UrlSchemeHandler::handleContentRequest(QWebEngineUrlRequestJob *request)
     BlobBuffer* buffer = new BlobBuffer(entry.getBlob());
     auto mimeType = QByteArray::fromStdString(entry.getMimetype());
     mimeType = mimeType.split(';')[0];
-    connect(buffer, &QIODevice::aboutToClose, buffer, &QObject::deleteLater);
+    // connect(buffer, &QIODevice::aboutToClose, buffer, &QObject::deleteLater);
+    connect(request, &QObject::destroyed, buffer, &QObject::deleteLater);
```
Comment (jetownfeve21) [inline src/urlschemehandler.cpp]: it seems that the deletion of the buffer is the cause of the random crash
According to the doc, it can be deleted like this.

image

https://doc.qt.io/qt-5/qwebengineurlrequestjob.html#reply

File: src/webview.cpp [hunk 3]
```diff
@@ -14,10 +14,21 @@ WebView::WebView(QWidget *parent)
...
+    connect(this, &QWebEngineView::loadFinished, this, [=](bool test) {
+        if (test) {
+            qInfo() << "good";
+        } else {
+            qInfo() << "not good";
+        }
+    });
+    connect(this, &QWebEngineView::loadStarted, this, [=]() {
+            qInfo() << "load start";
+    });
```
Comment (jetownfeve21) [inline src/webview.cpp]: only debug

**Comment by mgautierfr** [comment]
Good catch
