### PR TITLE
Fixed Tab and Bookmark Right to Left Layout Drawing

### LINKED ISSUE #1142: Title tab left padding is not OK
See
image

Pretty sure this is a regression, but not clear when it has been introduced

### PR DESCRIPTION
**Pull request by ShaopengLin**
Improve #594 Fix #1142 

Changes:
- Tab text alignment in RTL mode fixed. It was showing the tail of the title instead of the start.
- The left border of tabs was missing in RTL. Now each tab has both a left and right border. This makes the border a little thicker than before, but better UX than no border.
- I forgot to add the border on both sides when I refactored the search bar, which meant it has no left border in RTL mode. Fixed
- Title text now also has 2px padding.

### CODE REVIEW

**Review by kelson42 — CHANGES_REQUESTED** [review]
If you look to the icon, there is now a vertical alignement problem: I don't see why the two "Ted" Icon, and title should not be aligned!

**Comment by ShaopengLin** [comment]
Screenshot from 2024-07-30 01-41-25

@kelson42 The text is technically aligned to the icon. It is just the font size on the icon is different. If I misunderstood could you provide a screen shot of your alignment situation?

**Comment by ShaopengLin** [comment]
Ignore my previous comment, It does seem the text is not aligning with respect to the icon...

**Comment by kelson42** [comment]
@ShaopengLin Please look at all this alignment/margin at the pixel level, so things look perfect.

**Comment by ShaopengLin** [comment]
@kelson42 Additional Fixes:
1. Fixed the text to icon alignment.
2. The tab bottom border disappears when it is the current tab. The icon is up by 1px. Text painting now adjusts to this change as well.
3. Close button also does not adjust to the border disappearance. Fixed as well.

**Comment by kelson42** [comment]
Sorry, but this is still wrong:
image

* OK: What is green is OK, so the text is properly ligned verticaly
* OK: Top and bottom padding are the same at 5px, which is fine to me
* NOK: But why it left and right padding at 4px?! Should be 5 as well (or put 4pixel padding everywhere)
* NOK: Icon is 2 pixels too high!

**Comment by ShaopengLin** [comment]
@kelson42 The weird behavior is from our padding and border handling. Now the padding should be 4px. The bottom padding is the same, we are just painting the border white as part of the focus animation.

Screenshot from 2024-07-30 17-06-09

**Review by kelson42 — APPROVED** [review]
LGTM
@veloman-yunkan Good for the code review

File: src/tabbar.cpp [hunk 1]
```diff
@@ -463,7 +463,7 @@ void TabBar::paintEvent(QPaintEvent *e)
 
         int align = Qt::AlignVCenter;
         if (need_fade_out) {
-            align |= (right_to_left)? Qt::AlignRight : Qt::AlignLeft;
+            align |= (textRightToLeft == appRightToLeft) ? Qt::AlignLeft : Qt::AlignRight;
```
Comment (veloman-yunkan) [inline src/tabbar.cpp:471]: This looks strange. Why is the case of `textRightToLeft` and `appRightToLeft` both being `false` aligned the same way as when both of them are `true`?

Comment (ShaopengLin) [reply src/tabbar.cpp:471]: I will retest this and either make a explanation and visual, or correct it. A comment I believe will be needed here to explain the textbox behaviours.

Comment (ShaopengLin) [reply src/tabbar.cpp:471]: The alignment in RTL is flipped, i.e. if you set Align Left, it will actually align it to the right. https://doc.qt.io/qt-6/qtquick-positioning-righttoleft.html.

**Comment by ShaopengLin** [comment]
@veloman-yunkan @kelson42  I just noticed that the padding code here isn't working as wanted in Qt6.2. I will make a change and then we can re-review.

**Comment by ShaopengLin** [comment]
Done

File: src/tabbar.cpp [hunk 2]
```diff
@@ -427,6 +427,16 @@ void TabBar::paintEvent(QPaintEvent *e)
...
+#if QT_VERSION < QT_VERSION_CHECK(6, 0, 0)
+        // Add Padding to left, right. Padding is 4px. Add 5 to account for 
+        // Extra pixel from border.
+        tabTextRect.setX(tabTextRect.x() + 5);
+        tabTextRect.setWidth(tabTextRect.width() - 5);
+#else
+        // Qt6 correctly adds left and right padding but now incorrectly adds
+        // top or bottom padding.
+        tabTextRect.setY(tabTextRect.y() - 4);
+#endif
```
Comment (veloman-yunkan) [inline src/tabbar.cpp:439]: Magic numbers are evil. Please introduce a local constant (`const int padding = 4)` with a comment linking it to the value of `QTabBar::tab::padding` in `resources/css/style.css` (also add a sibling comment in `resources/css/style.css`).

Comment (ShaopengLin) [reply src/tabbar.cpp]: Done

**Review by veloman-yunkan — APPROVED** [review]
LGTM

@kelson42 Please test again before merging
