### PR TITLE
Fix content-type filtering

### LINKED ISSUE #792: Content Type filters are not working
image

### PR DESCRIPTION
**Pull request by mgautierfr**
The commit cb63bb2 was buggy and deactivate filtering by contentType.
We now handle two different lists to store tags we want and tags we don't.

Related to #791 
Fix #792

### CODE REVIEW

**Review by juuz0 — APPROVED** [review]

File: src/contentmanager.cpp [hunk 1]
```diff
@@ -392,30 +392,30 @@ void ContentManager::setSearch(const QString &search)
...
     for (auto &contentTypeFilter : m_contentTypeFilters) {
         auto state = contentTypeFilter->checkState();
         auto filter = contentTypeFilter->getName();
         if (state == Qt::PartiallyChecked) {
-            tags.push_back("_" + filter.toStdString() +":yes");
+            acceptTags.push_back("_" + filter.toStdString() +":yes");
         } else if (state == Qt::Checked) {
-            tags.push_back("_" + filter.toStdString() +":no");
+            acceptTags.push_back("_" + filter.toStdString() +":no");
         }
```
Comment (veloman-yunkan) [inline src/contentmanager.cpp:414]: I wonder why a partially checked state is translated to a "_contenttype:yes" tag and a fully checked state to a "_contenttype:no" tag

Comment (mgautierfr) [reply src/contentmanager.cpp:414]: The button is a 3 states button (`yes`, `no` and `no filtering`).
The 3 states available from Qt are `Checked`, `PartiallyChecked` and `Unchecked`.
We set the button ui here : https://github.com/kiwix/kiwix-desktop/blob/master/src/contenttypefilter.cpp#L8-L12

**Review by kelson42 — APPROVED** [review]
@mgautierfr Thank you! LGTM

File: src/contentmanager.cpp (hunk 1 above)
Comment (veloman-yunkan) [reply src/contentmanager.cpp:414]: Such mapping of various checked states to filter states is a little confusing. Anyway, your explanation allows to conclude that everything is correct here.

**Review by veloman-yunkan — APPROVED** [review]
