### PR TITLE
Unresponsive desktopapp server down fix

### LINKED ISSUE #121: kiwix-desktop becomes unresponsive if library.kiwix.org is down.
We should be resilient to error on the server side.

### PR DESCRIPTION
**Pull request by jetownfeve21**
Fixes #121

### CODE REVIEW

File: src/remotelibrarymanager.h [hunk 1]
```diff
@@ -0,0 +1,32 @@
+#ifndef REMOTELIBRARYMANAGER_H
+#define REMOTELIBRARYMANAGER_H
+
+#include <QObject>
+#include <QtNetwork>
+#include <kiwix/library.h>
+#include <kiwix/manager.h>
+
+class RemoteLibraryManager : public QObject
```
Comment (mgautierfr) [inline src/remotelibrarymanager.h]: I would name it differently.
This class doesn't handle (manage) a remote library. It handle a request to the server to get the result of a new
request.
Something like OpdsRequestManager would be better.

We could even go further. If the class is responsible to handle request to an opds server, we could (should) move the url creation in `ContentManager::updateLibrary` into this class.

---
Or this is really a RemoteLibraryManager, and so it should handle a library. And so to have `ContentManager::updateRemoteLibrary` implemented here.

File: src/remotelibrarymanager.h [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+
+public:
+    void doUpdate(const QUrl &url);
+
+private:
+    QNetworkAccessManager m_networkManager;
+    QNetworkReply *mp_reply;
+
+signals:
+    void booksChanged(const QString&);
```
Comment (mgautierfr) [inline src/remotelibrarymanager.h]: This signal is emit when we get a response, not when the books have changed.
So it should be name "requestReceived", "newOpdsStream", ...

File: src/remotelibrarymanager.cpp [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+RemoteLibraryManager::RemoteLibraryManager()
+: mp_reply(nullptr)
+{
+}
+
+void RemoteLibraryManager::doUpdate(const QUrl &url)
+{
+    QNetworkRequest request(url);
+    if (mp_reply) {
+        mp_reply->abort();
```
Comment (mgautierfr) [inline src/remotelibrarymanager.cpp]: Should we also call `mp_reply->deleteLater()` ?

File: src/contentmanager.cpp [hunk 4]
```diff
@@ -242,14 +244,18 @@ void ContentManager::updateLibrary() {
...
     url.setPath("/catalog/search");
     url.setQuery(query);
+    
     qInfo() << "Downloading" << url.toString(QUrl::FullyEncoded);
-    m_remoteLibrary = kiwix::Library();
-    kiwix::Manager manager(&m_remoteLibrary);
     try {
-        auto allContent = kiwix::download(url.toString(QUrl::FullyEncoded).toStdString());
-        manager.readOpds(allContent, CATALOG_URL);
+        m_remoteLibrary = kiwix::Library();
```
Comment (mgautierfr) [inline src/contentmanager.cpp]: This is an open question here: Should we "reset" the library when we do the request (so here), or when we receive
the response of the request (so in updateRemoteLibrary) ?

File: src/contentmanager.h [hunk 5]
```diff
@@ -45,6 +45,7 @@ class ContentManager : public QObject
     void booksChanged();
     void downloadsChanged();
     void currentLangChanged();
+    void displayLoadIcon(const bool);
```
Comment (mgautierfr) [inline src/contentmanager.h]: I wonder if we could name it differently.
`displayLoadIcon` is more about what to do with this signal. But the signal should be about what is going on.
Something like `pendingRequest` or `Loading`. It would be to the slot of the signal to decide what to do when a request is pending (display a loading icon).

File: src/contentmanager.cpp [hunk 6]
```diff
@@ -26,6 +26,7 @@ ContentManager::ContentManager(Library* library, kiwix::Downloader* downloader,
     connect(mp_library, &Library::booksChanged, this, [=]() {emit(this->booksChanged());});
     connect(this, &ContentManager::filterParamsChanged, this, &ContentManager::updateLibrary);
     connect(&m_remoteLibraryManager, &RemoteLibraryManager::booksChanged, this, &ContentManager::updateRemoteLibrary);
+    connect(&m_remoteLibraryManager, &RemoteLibraryManager::booksChanged, this, [=]() {emit(this->displayLoadIcon(false));});
```
Comment (mgautierfr) [inline src/contentmanager.cpp]: Could this signal being emit in `ContentManager::updateRemoteLibrary` instead of creating a new connection ?

File: src/contentmanager.cpp (hunk 4 above)
Comment (jetownfeve21) [reply src/contentmanager.cpp]: i don't see big differences between these two options.

File: src/remotelibrarymanager.cpp (hunk 3 above)
Comment (jetownfeve21) [reply src/remotelibrarymanager.cpp]: When mp_reply->abort() is called, it emits a 'finished' signal which is connected to the slot "receivedContent" where I already call mp_reply->deleteLater() so I think not.

https://github.com/kiwix/kiwix-desktop/blob/2bf05ddb6c4a6f0b1fdb2bcd0d2b4d2f0b2630d9/src/remotelibrarymanager.cpp#L8-L28

File: src/remotelibrarymanager.h (hunk 1 above)
Comment (jetownfeve21) [reply src/remotelibrarymanager.h]: Why do we use macro for the url's creation ? 

https://github.com/kiwix/kiwix-desktop/blob/a005a5cb2580d44a980a316e4a710011dceec659/src/contentmanager.cpp#L223-L225

Comment (mgautierfr) [reply src/remotelibrarymanager.h]: This is :
- 1. to move constants out of the code.
- 2. give some meanings to the constant.

It seems pretty obvious that in `url.setPort(80);`, `80` is the port of the request, and so probably the port of the catalog server.
But `CATALOG_HOST` and `CATALOG_URL`, despite they have the same values, are not the same things.
`CATALOG_HOST` is the host. So, no port or path.
`CATALOG_URL` is the (full) url of the catalog endpoint. It is use by the library to reconstruct absolute urls from relative ones include in the opds stream. It include at least the port. If the port is different from 80, `CATALOG_URL` should include it and be different than `CATALOG_HOST`.

If we directly put the string in the code, we lost the ideas that they are different things.

File: src/remotelibrarymanager.cpp (hunk 3 above)
Comment (mgautierfr) [reply src/remotelibrarymanager.cpp]: We are good so.

File: src/contentmanager.cpp [hunk 7]
```diff
@@ -232,36 +234,24 @@ void ContentManager::setCurrentCategoryFilter(QString category)
...
+        emit(pendingRequest(true));
+        m_remoteLibrary = kiwix::Library();
+        m_remoteLibraryManager.doUpdate(m_currentLanguage, m_categoryFilter);
     } catch (runtime_error&) {}
-    emit(booksChanged());
+}
+
+void ContentManager::updateRemoteLibrary(const QString& content) {
+    kiwix::Manager manager(&m_remoteLibrary);        
+    manager.readOpds(content.toStdString(), "library.kiwix.org");
```
Comment (mgautierfr) [inline src/contentmanager.cpp]: We should keep CATALOG_URL here. (And keep its definition in `src/contentmanagaer.cpp` instead of moving it in `src/opdsrequestmanager.cpp` where it is never used.

File: src/contentmanager.cpp (hunk 4 above)
Comment (mgautierfr) [reply src/contentmanager.cpp]: Rethinking about it, it would prefer to se the reset of the library in `updateRemoteLibrary`.
The need for a clear library is required by the fact that the manager doesn't remove books.
This is an implementation detail and it should be an internal step of `updateRemoteLibrary`.
